### ISSUE TITLE
Unable to use this lib

### ISSUE THREAD

**Issue by MrPresidentWhite** [LGatodu47/CatConfigMC#1]
when i'm importing this lib in my build.gradle like in the readme, i can't use it in my project because intellij says it cannot resolve the symbol "CatConfig". I whanted to use this lib because i whant to make a mod like ScreenshotViewer but with some extra features.

**Comment by LGatodu47** [comment]
Add the line `implementation 'io.github.lgatodu47:catconfig:0.3.0'` in the dependencies. I don't know why but this happened to me only recently. It seems that sometimes it will include it automatically and sometimes it won't.
